[package]
name = "rust_a"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

polars = "0.46.0"
csv = "1.3.1" 
plotters = "0.3.7"
serde = "1.0.219"
rand = "0.9.1"